# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52e1f2d0eaa0750a94b8eba672efcea63cd54fb782f8db289b6223227aba0ae093fc20f9c6bd3b4aecf0a5aedaf4687a40b9be1982f69e16fceec11c01fa6168

test:
  secret_key_base: 2cf47fdb455c7db0be9c1b7553d3ecca84fde9c27ee4f144adf5fbd117e4bc905c5d7fb5b0ac9576233e8a7cdec9f0a8f9421910a6cdc6531a1875b0b370a26b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
